config/routes.rb
Rails.application.routes.draw do
  root 'people#index'
  resources :people do
    resources :details
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/detail.rb
class Detail < ApplicationRecord
	belongs_to :person
	validates :email, presence: true
end

app/models/person.rb
class Person < ApplicationRecord
  has_many :details, dependent: :destroy
  validates :name, presence: true

  accepts_nested_attributes_for :details
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/details_controller.rb
class DetailsController < ApplicationController
  before_action :set_person_and_detail, only: %i[show new create edit update destroy]

  def new
    @detail = @person.details.new
  end

  def edit
  end

  def create
    @detail = @person.details.new(detail_params)

    if @detail.save
      redirect_to @person
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @detail.update(detail_params)
      redirect_to @person
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @detail.destroy
    redirect_to @person, notice: "Detail was successfully destroyed."
  end

  private

  def set_person_and_detail
    @person = Person.find_by(id: params[:person_id])
    @detail = Detail.find(params[:id]) if params[:id].present?
  end

  def detail_params
    params.require(:detail).permit(:email, :phone)
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: %i[show edit update destroy]

  def index
    @people = Person.all
  end

  def show
    @details = @person.details
    respond_to do |format|
      format.html
      format.turbo_stream 
    end
  end

  def new
    @person = Person.new
  end

  def edit
  end

  def create
    @person = Person.new(person_params)
    if @person.save
      redirect_to @person, notice: "Person was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @person.update(person_params)
      redirect_to @person, notice: "Person was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @person.destroy
    redirect_to root_path, notice: "Person was successfully destroyed."
  end

  private

  def set_person
    @person = Person.find(params[:id])
  end

  def person_params
    params.require(:person).permit(:title, :name, :age)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/details_helper.rb
module DetailsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/details/_form.html.erb
<% path = detail.id.nil? ? person_details_path : person_detail_path(detail.person, detail) %>
<%= form_with(model: detail, url: path) do |form| %>
  <% if @detail.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@detail.errors.count, "error") %> prohibited this detail from being saved:</h2>

      <ul>
        <% @detail.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :phone, style: "display: block" %>
    <%= form.text_field :phone %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/details/edit.html.erb
<%= turbo_stream_from 'add_details' %>

<%= turbo_frame_tag 'add_details' do %>
  <h1>Editing detail</h1>
  <%= render "form", detail: @detail %>
<% end %>

app/views/details/new.html.erb
<%= turbo_stream_from 'add_details' %>

<%= turbo_frame_tag 'add_details' do %>
  <h1>New detail</h1>
  <%= render "form", detail: @detail, person: @person %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AssessmentRuby</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <style>
      .container {
        display: flex;
      }

      .people-list {
        flex: 1;
        padding-right: 20px;
        margin: 20px;
      }

      .person-details {
        margin_top: 20px;
        flex: 1;
      }
    </style>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/people/_form.html.erb
<%= form_with(model: person) do |form| %>
  <% if person.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
        <% person.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :age, style: "display: block" %>
    <%= form.number_field :age %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/people/_people.html.erb
<h1>Persons</h1>
<h3><%= link_to "Add Person", new_person_path, remote: true, data: { turbo_frame: 'details' } %></h3><br>

<% people.each do |person| %>
 <h3> <%= link_to person.name, person_path(person), remote: true, class: "person-link", data: { turbo_frame: 'details' } %></h3>
  <%= link_to "Edit", edit_person_path(person), remote: true, data: { turbo_frame: 'details' } %>
  <%= link_to "Destroy", person_path(person), remote: true, data: { "turbo-method": "delete" } %>
<% end %>

app/views/people/_show.html.erb
<%= turbo_stream_from 'details' %>

<%= turbo_frame_tag 'details' do %>
  <h2>Name: <%= person.name %></h2>
  <h3>Title: <%= person.title %></h3>
  <h3>Age: <%= person.age %></h3>
  <%= turbo_frame_tag 'add_details' do %>
    <%= link_to "Add details", new_person_detail_path(person), remote: true %>
  <% end %>

  <% details.each do |detail| %>
    <div class="detail-item">
      <h3>Email: <%= detail.email %></h3>
      <h3>Phone: <%= detail.phone %></h3>
      <%= link_to "Edit", edit_person_detail_path(person, detail), remote: true, data: { turbo_frame: 'add_details' }  %>
      <%= link_to "Destroy", person_detail_path(person, detail), remote: true, data: { "turbo-method": "delete" } %>
    </div>
  <% end %>
<% end %>

app/views/people/edit.html.erb
<%= turbo_stream_from 'details' %>

<%= turbo_frame_tag 'details' do %>
  <h1>Editing person</h1>
  <%= render "form", person: @person %>
<% end %>

app/views/people/index.html.erb
<div class="container">
  <div class="people-list">
    <%= turbo_stream_from 'people' %>
    <%= turbo_frame_tag 'people' do %>
      <%= render "people", people: @people %>
    <% end %>
  </div>
  <div class="person-details" id="person-details">
    <%= turbo_frame_tag 'details' do %>
      <% if @people.present? %>
        <%= render 'show', details: @people.first.details, person: @people.first %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/people/new.html.erb
<%= turbo_stream_from 'details' %>

<%= turbo_frame_tag 'details' do %>
  <h1>New person</h1>
  <%= render "form", person: @person %>
<% end %>

app/views/people/show.html.erb
<%= turbo_stream_from 'details' %>

<%= turbo_frame_tag 'details' do %>
  <%= render 'show', details: @details, person: @person %>
<% end %>

app/views/people/show.turbo_stream.erb
<turbo-stream action="replace" target="people">
  <template>
    <h1>Persons</h1>
    <h3><%= link_to "Add Person", new_person_path, remote: true, data: { turbo_frame: 'details' } %></h3><br>

    <% Person.all.each do |person| %>
     <h3> <%= link_to person.name, person_path(person), remote: true, class: "person-link", data: { turbo_frame: 'details' } %></h3>
      <%= link_to "Edit", edit_person_path(person), remote: true, data: { turbo_frame: 'details' } %>
      <%= link_to "Destroy", person_path(person), remote: true, data: { "turbo-method": "delete" } %>
    <% end %>
  </template>
</turbo-stream>
<turbo-stream action="replace" target="details">
  <template>
    <h2>Name: <%= @person.name %></h2>
    <h3>Title: <%= @person.title %></h3>
    <h3>Age: <%= @person.age %></h3>
    <%= turbo_frame_tag 'add_details' do %>
      <%= link_to "Add details", new_person_detail_path(@person), remote: true %>
    <% end %>

    <% @person.details.each do |detail| %>
      <div class="detail-item">
        <h3>Email: <%= detail.email %></h3>
        <h3>Phone: <%= detail.phone %></h3>
        <%= link_to "Edit", edit_person_detail_path(@person, detail), remote: true, data: { turbo_frame: 'add_details' } %>
        <%= link_to "Destroy", person_detail_path(@person, detail), remote: true, data: { "turbo-method": "delete" } %>
      </div>
    <% end %>
  </template>
</turbo-stream>